import { Test, TestingModule } from '@nestjs/testing';
import { QuoteEmailService } from '../email-templates/quote-email.service';
import { QuotesService } from '../quotes.service';
import { QuoteStatus, CompanyStatus, QuotePriority, UserStatus, UserRole } from '@prisma/client';

describe('QuoteEmailService', () => {
    let service: QuoteEmailService;
    let quotesService: QuotesService;

    beforeEach(async () => {
        const module: TestingModule = await Test.createTestingModule({
            providers: [
                QuoteEmailService,
                {
                    provide: QuotesService,
                    useValue: {
                        findOne: jest.fn(),
                    },
                },
            ],
        }).compile();

        service = module.get<QuoteEmailService>(QuoteEmailService);
        quotesService = module.get<QuotesService>(QuotesService);
    });

    it('should be defined', () => {
        expect(service).toBeDefined();
    });

    describe('generateQuoteEmail', () => {
        it('should generate a creation email template', async () => {
            const mockQuote = {
                id: 'test-quote-id',
                quoteNumber: 'QTE-2301-0001',
                title: 'Test Quote',
                description: 'Test quote description',
                status: QuoteStatus.SENT,
                priority: QuotePriority.MEDIUM,
                subtotal: 1000,
                taxAmount: 180,
                discountAmount: 0,
                totalAmount: 1180,
                validUntil: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
                sentAt: new Date(),
                viewedAt: null,
                acceptedAt: null,
                rejectedAt: null,
                expiredAt: null,
                clientId: 'test-client-id',
                client: {
                    id: 'test-client-id',
                    name: 'Test Company',
                    legalName: 'Test Company Inc.',
                    taxId: '123456789',
                    status: CompanyStatus.CLIENT,
                    address: '123 Test St',
                    city: 'Test City',
                    state: 'TS',
                    postalCode: '12345',
                    country: 'Test Country',
                    email: 'test@company.com',
                    phone: '123-456-7890',
                    website: 'www.testcompany.com',
                    paymentTerms: 30,
                    currency: 'USD',
                    taxRate: 0.18,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                    deletedAt: null,
                },
                assignedToId: 'test-user-id',
                assignedTo: {
                    id: 'test-user-id',
                    email: 'test@example.com',
                    firstName: 'Test',
                    lastName: 'User',
                    password: 'password',
                    role: UserRole.SALES_REP,
                    status: UserStatus.ACTIVE,
                    emailVerified: true,
                    emailVerifiedAt: new Date(),
                    lastLoginAt: new Date(),
                    failedLoginAttempts: 0,
                    lockedUntil: null,
                    refreshToken: null,
                    refreshTokenExpiresAt: null,
                    profilePicture: null,
                    phone: '123-456-7890',
                    timezone: 'UTC',
                    language: 'es',
                    twoFactorEnabled: false,
                    twoFactorSecret: null,
                    googleId: null,
                    linkedinId: null,
                    dataConsentGiven: true,
                    dataConsentDate: new Date(),
                    dataRetentionDate: null,
                    companyId: null,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                    deletedAt: null,
                },
                createdById: 'test-user-id',
                createdBy: {
                    id: 'test-user-id',
                    email: 'test@example.com',
                    firstName: 'Test',
                    lastName: 'User',
                    password: 'password',
                    role: UserRole.SALES_REP,
                    status: UserStatus.ACTIVE,
                    emailVerified: true,
                    emailVerifiedAt: new Date(),
                    lastLoginAt: new Date(),
                    failedLoginAttempts: 0,
                    lockedUntil: null,
                    refreshToken: null,
                    refreshTokenExpiresAt: null,
                    profilePicture: null,
                    phone: '123-456-7890',
                    timezone: 'UTC',
                    language: 'es',
                    twoFactorEnabled: false,
                    twoFactorSecret: null,
                    googleId: null,
                    linkedinId: null,
                    dataConsentGiven: true,
                    dataConsentDate: new Date(),
                    dataRetentionDate: null,
                    companyId: null,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                    deletedAt: null,
                },
                items: [
                    {
                        id: 'test-item-id',
                        quoteId: 'test-quote-id',
                        description: 'Test Item',
                        quantity: 1,
                        unitPrice: 1000,
                        unit: 'unit',
                        discount: 0,
                        taxRate: 0.18,
                        totalPrice: 1180,
                        serviceId: null,
                        order: 0,
                        createdAt: new Date(),
                        updatedAt: new Date(),
                    },
                ],
                versions: [],
                project: null,
                invoices: [],
                createdAt: new Date(),
                updatedAt: new Date(),
                deletedAt: null,
            };

            jest.spyOn(quotesService, 'findOne').mockResolvedValue(mockQuote);

            const result = await service.generateQuoteEmail('test-quote-id', 'creation');
            expect(result).toBeDefined();
            expect(result.subject).toContain(mockQuote.quoteNumber);
            expect(result.html).toContain(mockQuote.quoteNumber);
            expect(result.text).toContain(mockQuote.quoteNumber);
        });

        it('should generate a reminder email template', async () => {
            const mockQuote = {
                id: 'test-quote-id',
                quoteNumber: 'QTE-2301-0001',
                title: 'Test Quote',
                description: 'Test quote description',
                status: QuoteStatus.SENT,
                priority: QuotePriority.MEDIUM,
                subtotal: 1000,
                taxAmount: 180,
                discountAmount: 0,
                totalAmount: 1180,
                validUntil: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
                sentAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
                viewedAt: null,
                acceptedAt: null,
                rejectedAt: null,
                expiredAt: null,
                clientId: 'test-client-id',
                client: {
                    id: 'test-client-id',
                    name: 'Test Company',
                    legalName: 'Test Company Inc.',
                    taxId: '123456789',
                    status: CompanyStatus.CLIENT,
                    address: '123 Test St',
                    city: 'Test City',
                    state: 'TS',
                    postalCode: '12345',
                    country: 'Test Country',
                    email: 'test@company.com',
                    phone: '123-456-7890',
                    website: 'www.testcompany.com',
                    paymentTerms: 30,
                    currency: 'USD',
                    taxRate: 0.18,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                    deletedAt: null,
                },
                assignedToId: 'test-user-id',
                assignedTo: {
                    id: 'test-user-id',
                    email: 'test@example.com',
                    firstName: 'Test',
                    lastName: 'User',
                    password: 'password',
                    role: UserRole.SALES_REP,
                    status: UserStatus.ACTIVE,
                    emailVerified: true,
                    emailVerifiedAt: new Date(),
                    lastLoginAt: new Date(),
                    failedLoginAttempts: 0,
                    lockedUntil: null,
                    refreshToken: null,
                    refreshTokenExpiresAt: null,
                    profilePicture: null,
                    phone: '123-456-7890',
                    timezone: 'UTC',
                    language: 'es',
                    twoFactorEnabled: false,
                    twoFactorSecret: null,
                    googleId: null,
                    linkedinId: null,
                    dataConsentGiven: true,
                    dataConsentDate: new Date(),
                    dataRetentionDate: null,
                    companyId: null,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                    deletedAt: null,
                },
                createdById: 'test-user-id',
                createdBy: {
                    id: 'test-user-id',
                    email: 'test@example.com',
                    firstName: 'Test',
                    lastName: 'User',
                    password: 'password',
                    role: UserRole.SALES_REP,
                    status: UserStatus.ACTIVE,
                    emailVerified: true,
                    emailVerifiedAt: new Date(),
                    lastLoginAt: new Date(),
                    failedLoginAttempts: 0,
                    lockedUntil: null,
                    refreshToken: null,
                    refreshTokenExpiresAt: null,
                    profilePicture: null,
                    phone: '123-456-7890',
                    timezone: 'UTC',
                    language: 'es',
                    twoFactorEnabled: false,
                    twoFactorSecret: null,
                    googleId: null,
                    linkedinId: null,
                    dataConsentGiven: true,
                    dataConsentDate: new Date(),
                    dataRetentionDate: null,
                    companyId: null,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                    deletedAt: null,
                },
                items: [
                    {
                        id: 'test-item-id',
                        quoteId: 'test-quote-id',
                        description: 'Test Item',
                        quantity: 1,
                        unitPrice: 1000,
                        unit: 'unit',
                        discount: 0,
                        taxRate: 0.18,
                        totalPrice: 1180,
                        serviceId: null,
                        order: 0,
                        createdAt: new Date(),
                        updatedAt: new Date(),
                    },
                ],
                versions: [],
                project: null,
                invoices: [],
                createdAt: new Date(),
                updatedAt: new Date(),
                deletedAt: null,
            };

            jest.spyOn(quotesService, 'findOne').mockResolvedValue(mockQuote);

            const result = await service.generateQuoteEmail('test-quote-id', 'reminder');
            expect(result).toBeDefined();
            expect(result.subject).toContain('Reminder');
            expect(result.html).toContain('reminder');
        });
    });

    describe('sendQuoteEmail', () => {
        it('should send a quote email (simulated)', async () => {
            const mockQuote = {
                id: 'test-quote-id',
                quoteNumber: 'QTE-2301-0001',
                title: 'Test Quote',
                description: 'Test quote description',
                status: QuoteStatus.SENT,
                priority: QuotePriority.MEDIUM,
                subtotal: 1000,
                taxAmount: 180,
                discountAmount: 0,
                totalAmount: 1180,
                validUntil: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
                sentAt: new Date(),
                viewedAt: null,
                acceptedAt: null,
                rejectedAt: null,
                expiredAt: null,
                clientId: 'test-client-id',
                client: {
                    id: 'test-client-id',
                    name: 'Test Company',
                    legalName: 'Test Company Inc.',
                    taxId: '123456789',
                    status: CompanyStatus.CLIENT,
                    address: '123 Test St',
                    city: 'Test City',
                    state: 'TS',
                    postalCode: '12345',
                    country: 'Test Country',
                    email: 'test@company.com',
                    phone: '123-456-7890',
                    website: 'www.testcompany.com',
                    paymentTerms: 30,
                    currency: 'USD',
                    taxRate: 0.18,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                    deletedAt: null,
                },
                assignedToId: 'test-user-id',
                assignedTo: {
                    id: 'test-user-id',
                    email: 'test@example.com',
                    firstName: 'Test',
                    lastName: 'User',
                    password: 'password',
                    role: UserRole.SALES_REP,
                    status: UserStatus.ACTIVE,
                    emailVerified: true,
                    emailVerifiedAt: new Date(),
                    lastLoginAt: new Date(),
                    failedLoginAttempts: 0,
                    lockedUntil: null,
                    refreshToken: null,
                    refreshTokenExpiresAt: null,
                    profilePicture: null,
                    phone: '123-456-7890',
                    timezone: 'UTC',
                    language: 'es',
                    twoFactorEnabled: false,
                    twoFactorSecret: null,
                    googleId: null,
                    linkedinId: null,
                    dataConsentGiven: true,
                    dataConsentDate: new Date(),
                    dataRetentionDate: null,
                    companyId: null,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                    deletedAt: null,
                },
                createdById: 'test-user-id',
                createdBy: {
                    id: 'test-user-id',
                    email: 'test@example.com',
                    firstName: 'Test',
                    lastName: 'User',
                    password: 'password',
                    role: UserRole.SALES_REP,
                    status: UserStatus.ACTIVE,
                    emailVerified: true,
                    emailVerifiedAt: new Date(),
                    lastLoginAt: new Date(),
                    failedLoginAttempts: 0,
                    lockedUntil: null,
                    refreshToken: null,
                    refreshTokenExpiresAt: null,
                    profilePicture: null,
                    phone: '123-456-7890',
                    timezone: 'UTC',
                    language: 'es',
                    twoFactorEnabled: false,
                    twoFactorSecret: null,
                    googleId: null,
                    linkedinId: null,
                    dataConsentGiven: true,
                    dataConsentDate: new Date(),
                    dataRetentionDate: null,
                    companyId: null,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                    deletedAt: null,
                },
                items: [
                    {
                        id: 'test-item-id',
                        quoteId: 'test-quote-id',
                        description: 'Test Item',
                        quantity: 1,
                        unitPrice: 1000,
                        unit: 'unit',
                        discount: 0,
                        taxRate: 0.18,
                        totalPrice: 1180,
                        serviceId: null,
                        order: 0,
                        createdAt: new Date(),
                        updatedAt: new Date(),
                    },
                ],
                versions: [],
                project: null,
                invoices: [],
                createdAt: new Date(),
                updatedAt: new Date(),
                deletedAt: null,
            };

            jest.spyOn(quotesService, 'findOne').mockResolvedValue(mockQuote);

            const result = await service.sendQuoteEmail('test-quote-id', 'test@example.com', 'creation');
            expect(result).toBeDefined();
            expect(result.success).toBe(true);
            expect(result.email.to).toBe('test@example.com');
        });
    });
});